[package]
name = "constellation-engine"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.25.0"
# imgui = "0.8.0"
log = "0.4.0"
env_logger = "0.9.0"
futures = "0.3.17"
wgpu = "0.11.1"
bytemuck = "1.7.2"
ndarray = "0.15.3"
egui = "0.15.0"
clap = "2.34.0"
nalgebra = "0.29.0"

starlight = { path = "crates/starlight", version = "0.1.0" }

[workspace]

members = ["crates/*"]
