[package]
name = "constellation-engine"
version = "0.1.0"
edition = "2021"

[features]
simulation = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

clap = "2.34.0"
core = { path = "crates/core", version = "0.1.0" }
env_logger = "0.9.0"

[build-dependencies]

cmake = "0.1.48"

[workspace]

members = ["crates/*"]
