[package]
name = "constellation-engine"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.25.0"
imgui = "0.8.0"
log = "0.4.0"
env_logger = "0.9.0"
futures = "0.3.17"
wgpu = "0.11.0"
