cmake -S third-party/dealii -B packages/dealii ^
-D "DEAL_II_WITH_64BIT_INDICES=OFF" ^
-D "DEAL_II_WITH_ADOLC=OFF" ^
-D "DEAL_II_WITH_ARPACK=OFF" ^
-D "DEAL_II_WITH_ASSIMP=OFF" ^
-D "DEAL_II_WITH_CUDA=OFF" ^
-D "DEAL_II_WITH_CXX17=ON" ^
-D "DEAL_II_WITH_GINKGO=OFF" ^
-D "DEAL_II_WITH_GMSH=OFF" ^
-D "DEAL_II_WITH_GSL=OFF" ^
-D "DEAL_II_WITH_HDF5=OFF" ^
-D "DEAL_II_WITH_LAPACK=OFF" ^
-D "DEAL_II_WITH_METIS=OFF" ^
-D "DEAL_II_WITH_MPI=OFF" ^
-D "DEAL_II_WITH_MUPARSER=OFF" ^
-D "DEAL_II_WITH_NANOFLANN=OFF" ^
-D "DEAL_II_WITH_NETCDF=OFF" ^
-D "DEAL_II_WITH_OPENCASCADE=OFF" ^
-D "DEAL_II_WITH_P4EST=OFF" ^
-D "DEAL_II_WITH_PETSC=OFF" ^
-D "DEAL_II_WITH_SCALAPACK=OFF" ^
-D "DEAL_II_WITH_SLEPC=OFF" ^
-D "DEAL_II_WITH_SUNDIALS=OFF" ^
-D "DEAL_II_WITH_SYMENGINE=OFF" ^
-D "DEAL_II_WITH_TRILINOS=OFF" ^
-D "DEAL_II_WITH_UMFPACK=OFF" ^
-D "DEAL_II_WITH_ZLIB=OFF"

pause